Repository UKHomeOffice/hocs-docs, pull requests merged in 2022-05, with the labels that each got.

#236 HOCS-5032: Update Secrets to match prod format
  kube/kd/deployment.yaml
Labels: patch

#235 HOCS-5027: add dependabot GitHub Action update
  .github/dependabot.yml
Labels: skip-release

#246 HOCS-5032: Upgrade docker-compose and drone to use postgres 14
  docker/docker-compose.yml
Labels: skip-release

#245 Chore: Upgrade drone build image version
  .drone.yml
Labels: skip-release

#248 HOCS-5159: Add Deleted Timestamp metadata
  src/main/java/uk/gov/digital/ho/hocs/document/DocumentDataService.java
  src/main/java/uk/gov/digital/ho/hocs/document/client/auditclient/AuditClient.java
  src/main/java/uk/gov/digital/ho/hocs/document/model/DocumentData.java
  src/main/resources/db/migration/V1_4__ADD_DELETED_ON_COLUMN.sql
  src/test/java/uk/gov/digital/ho/hocs/document/DocumentServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/document/client/auditclient/AuditClientTest.java
Labels: minor
