Repository UKHomeOffice/hocs-docs, pull requests merged in 2022-03, with the labels that each got.

#204 HOCS-4696: use GitHub SemVer actions
  .drone.yml
  .github/workflows/label-check.yml
  .github/workflows/semver.yml
Labels: major

#203 HOCS-4682: add original file existence indicator
  src/main/java/uk/gov/digital/ho/hocs/document/dto/DocumentDto.java
Labels: minor

#210 HOCS-4696: Override Dependabot labels
  .github/dependabot.yml
Labels: patch

#209 HOCS-4696: Remove duplicate Sonar Run.
  .drone.yml
Labels: patch

#207 HOCS-4221: Add document transfer
  src/main/java/uk/gov/digital/ho/hocs/document/DocumentDataResource.java
  src/main/java/uk/gov/digital/ho/hocs/document/DocumentDataService.java
  src/main/java/uk/gov/digital/ho/hocs/document/client/auditclient/AuditClient.java
  src/main/java/uk/gov/digital/ho/hocs/document/dto/CopyDocumentsRequest.java
  src/main/java/uk/gov/digital/ho/hocs/document/model/DocumentData.java
  src/main/java/uk/gov/digital/ho/hocs/document/repository/DocumentRepository.java
  src/test/java/uk/gov/digital/ho/hocs/document/DocumentServiceTest.java
Labels: minor

#211 HOCS-4792: Improve logging on s3 Document Retrieval
  src/main/java/uk/gov/digital/ho/hocs/document/DocumentDataService.java
  src/main/java/uk/gov/digital/ho/hocs/document/application/LogEvent.java
  src/main/java/uk/gov/digital/ho/hocs/document/model/DocumentData.java
Labels: patch

#213 Hocs-4799: Update the base image to fix the drone build
  .drone.yml
Labels: patch

#214 Hocs-4799: Update the base image to fix the drone build
  .drone.yml
Labels: patch

#215 HOCS-4808: support tagging on support branches
  .drone.yml
Labels: patch
